theme: jekyll-theme-minimal
title: Corvus RSS Reader for Safari
description: Your personal RSS reader for Safari on macOS, iOS, and iPadOS
url: https://corvusdevs.github.io
baseurl: /Corvus-RSS-Reader-For-Safari
